services:
  frontend:
    build: .
    ports:
      - "8081:8081"
    volumes:
      - .:/app
      - /app/node_modules # ホストのnode_modulesで上書きされないようにする
    environment:
      - "EXPO_PACKAGER_PROXY_URL=http://${LOCAL_IP}:8081"
      - "REACT_NATIVE_PACKAGER_HOSTNAME=${LOCAL_IP}"
      - "EXPO_PUBLIC_LOCAL_IP=${LOCAL_IP}"
    stdin_open: true
    tty: true